CREATE DATABASE IF NOT EXISTS no_framework
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE no_framework;

CREATE TABLE IF NOT EXISTS `user` (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  remember_token VARCHAR(255),
  remember_identifier VARCHAR(255)
);
